- name: Create MySQL User 
  mysql_user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    login_user: "{{login_user}}"
    login_password: "{{ login_password }}"
    state: present

- name: Adds the specified privileges to specified user for specified database
  expect:
     command:  mysql -u {{name}} -p -e "GRANT ALL ON {{dbname}}.* to '{{login_user}}'@'{{host}}';"
     echo: yes
     responses:
        'password': "{{login_password}}"

- name: Flush Priviliges
  command: mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES"
