# tasks file for install.mysql
- name: Fix update problem
  shell: apt-get update --allow-releaseinfo-change

- name: Install MySQL packages
  apt:
    name: python3-pip
    state: present
    
- name: Install pexpect packages
  pip:
    name: pexpect
    state: present
    executable: pip3

- name: Upgrade pip to be able to install pymysql
  pip:
     name: pip
     extra_args: --upgrade
     executable: pip3

- name: Install pip PyMySQL package
  pip:
     name: PyMySQL
     executable: pip3

- name: Repo update
  become: true
  apt:
    update_cache: yes

- name: Install mariadb
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - mariadb-server
    - mariadb-client