---
- name: Update cache and upgrade if specified.
  become: true
  apt:
    update_cache: yes

- name: install nginx
  apt: 
    name: nginx
    state: present
    update_cache: yes

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
